### PR TITLE
Stats update

### LINKED ISSUE #217: Change plots message for ache crawls while crawl is running.

### LINKED ISSUE #220: Put summary statistics including number of images on crawls page.
Also get rid of the list of images on the crawls page.

### LINKED ISSUE #250: Persist stats in database

### PR DESCRIPTION
**Pull request by brittainhard**
This will be done before sunday.

closes #250 
closes #217 
closes #220

### CODE REVIEW

**Comment by brittainhard** [comment]
So I think this is ready to be merged, but I can't test the image stats against nutch crawls cause I can't get a nutch crawl to start.

**Comment by brittainhard** [comment]
hey @chdoig let me know what you are thinking on this PR whenever you've got time.

**Comment by chdoig** [comment]
I was having some issues when you try to get the status of a nutch crawl that hasn't been started yet. It throws an exception. Can you try to fix that?

**Comment by brittainhard** [comment]
This PR doesn't have any code related to that issue, but I know that Karan is working how crawl status is reported, so the best thing might be to make an issue with your traceback and refer him to it.

**Pull request merged**
